# Site settings
title: 你好世界
email: huhaiyung@gmail.com
description: Haiyung's Blog
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://unclebob.cn" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username:  Haiyung
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# use rouge locally, pygments in Github
# highlighter: pygments
# highlighter: rouge
# highlighter: false

timezone: TIMEZONE