# Site settings
title: Haiyung's Personal Website
author: Haiyung
email: huhaiyung@126.com
description: 关于世界与市场，关于技术与力量。
permalink: /:title

# Build settings
markdown: kramdown
timezone: Asia/Shanghai
future: true

twitter_username: huhaiyung
github_username: Haiyung
wechat_username: huhaiyung

defaults:
  - scope:
      path: "books"
    values:
      pdf: true
