# Site settings
title: Haiyung's Personal Website
baseurl: ""
author: Haiyung
email: huhaiyung@126.com
description: 关于世界与市场，关于技术与力量。
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
timezone: TIMEZONE
future: true

twitter_username: Haiyung
github_username: Haiyung
wechat_username: huhaiyung
