# Site settings
title: Haiyung's Personal Website
author: Haiyung
email: hhyplus@163.com
description: 关于世界与市场，关于技术与力量。
permalink: /:title

# Build settings
markdown: kramdown
timezone: Asia/Shanghai
future: true

twitter_username: hhyplus
github_username: Haiyung

defaults:
  - scope:
      path: "books"
    values:
      pdf: true
