# Site settings
title: 你好世界
baseurl: ""
author: Haiyung
email: huhaiyung@gmail.com
description: 关于世界与市场，关于技术与力量。
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
timezone: TIMEZONE

twitter_username: Haiyung
github_username:  Haiyung